# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/17xWNBIvLUxjHFo9BN8TulFW5VTdoyJQO
"""

x=(10+5)
print(x)

x=(10-5)
print(x)

x=5
    y=10
    print(x*y)

x=5
y=10
print(x/y)

a = "4110E003"
print(a)

for x in "4110E003":
  print(x)

a="4110E003"
print(a[0:4])

a = '''asdfghjklqwertyuiop'''
print(a)

thislist = ["4110E003", "ksu", "IE"]
print(thislist)

mylist = ["apple", "banana", "cherry"]
print(type(mylist))

thislist = list(("apple", "banana", "cherry")) 
print(thislist)

thislist = ["apple", "banana", "cherry"]
print(thislist[0])

thislist = ["apple", "banana", "cherry", "apple", "cherry"]
print(thislist)

thisdict = {
  "brand": "Ford",
  "model": "Mustang",
  "year": 1964
}
print(thisdict)

thisdict = {
  "brand": "Ford",
  "model": "Mustang",
  "year": 1964
}
print(thisdict["brand"])

thisdict = {
  "brand": "Ford",
  "model": "Mustang",
  "year": 1964
}
print(thisdict["year"])

thisdict = {
  "brand": "Ford",
  "model": "Mustang",
  "year": 1964,
  "year": 2020
}
print(thisdict)

thisdict = {
  "brand": "Ford",
  "model": "Mustang",
  "year": 1964
}
print(type(thisdict))

print(len(thisdict))